/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectakhir;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class menuAdminDPembelian extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public menuAdminDPembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btlogout = new javax.swing.JButton();
        btkurir = new javax.swing.JButton();
        Btdaftar = new javax.swing.JButton();
        btpengiriman = new javax.swing.JButton();
        btpembelian = new javax.swing.JButton();
        bgmenu = new javax.swing.JLabel();
        btsupplier = new javax.swing.JButton();
        btpelanggan = new javax.swing.JButton();
        pm = new javax.swing.JPanel();
        btsearchpm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtsearchpm = new javax.swing.JTextField();
        LBMIN = new javax.swing.JLabel();
        LBEXIT = new javax.swing.JLabel();
        pm1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pm2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listnamepm = new javax.swing.JList<>();
        txtidppm = new javax.swing.JTextField();
        txtidpm = new javax.swing.JTextField();
        txtidag = new javax.swing.JTextField();
        txtsubpm = new javax.swing.JTextField();
        txtjumlahpm = new javax.swing.JTextField();
        txtnamappm = new javax.swing.JTextField();
        btdelpm = new javax.swing.JButton();
        pm3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdetailpm = new javax.swing.JTable();
        btcetakpm = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 85, 85));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SPAREPART MOTOR");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 30));

        btlogout.setBackground(new java.awt.Color(204, 204, 204));
        btlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btlogout.setText("LOG OUT");
        btlogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 90, 30));

        btkurir.setBackground(new java.awt.Color(85, 85, 85));
        btkurir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btkurir.setForeground(new java.awt.Color(255, 255, 255));
        btkurir.setText("Kurir");
        btkurir.setBorder(new javax.swing.border.MatteBorder(null));
        btkurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkurirActionPerformed(evt);
            }
        });
        jPanel2.add(btkurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, -1));

        Btdaftar.setBackground(new java.awt.Color(85, 85, 85));
        Btdaftar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Btdaftar.setForeground(new java.awt.Color(255, 255, 255));
        Btdaftar.setText("Daftar sparepart");
        Btdaftar.setBorder(new javax.swing.border.MatteBorder(null));
        Btdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtdaftarActionPerformed(evt);
            }
        });
        jPanel2.add(Btdaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, -1));

        btpengiriman.setBackground(new java.awt.Color(85, 85, 85));
        btpengiriman.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btpengiriman.setForeground(new java.awt.Color(255, 255, 255));
        btpengiriman.setText("Detail pengiriman sprarepart");
        btpengiriman.setBorder(new javax.swing.border.MatteBorder(null));
        btpengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpengirimanActionPerformed(evt);
            }
        });
        jPanel2.add(btpengiriman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, -1));

        btpembelian.setBackground(new java.awt.Color(51, 51, 51));
        btpembelian.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btpembelian.setForeground(new java.awt.Color(255, 255, 255));
        btpembelian.setText("Detail pembelian");
        btpembelian.setBorder(new javax.swing.border.MatteBorder(null));
        btpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpembelianActionPerformed(evt);
            }
        });
        jPanel2.add(btpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, -1));

        bgmenu.setBackground(new java.awt.Color(0, 0, 0));
        bgmenu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        bgmenu.setForeground(new java.awt.Color(255, 255, 255));
        bgmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sparepart.jpg"))); // NOI18N
        bgmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgmenuMouseClicked(evt);
            }
        });
        jPanel2.add(bgmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 340, 190));

        btsupplier.setBackground(new java.awt.Color(85, 85, 85));
        btsupplier.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btsupplier.setForeground(new java.awt.Color(255, 255, 255));
        btsupplier.setText("supplier");
        btsupplier.setBorder(new javax.swing.border.MatteBorder(null));
        btsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsupplierActionPerformed(evt);
            }
        });
        jPanel2.add(btsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, -1));

        btpelanggan.setBackground(new java.awt.Color(85, 85, 85));
        btpelanggan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btpelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btpelanggan.setText("pelanggan");
        btpelanggan.setBorder(new javax.swing.border.MatteBorder(null));
        btpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpelangganActionPerformed(evt);
            }
        });
        jPanel2.add(btpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 570));

        pm.setBackground(new java.awt.Color(153, 153, 153));
        pm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pm.setForeground(new java.awt.Color(255, 255, 255));
        pm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btsearchpm.setText("Search");
        pm.add(btsearchpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 90, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        pm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));
        pm.add(txtsearchpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 510, 30));

        LBMIN.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LBMIN.setForeground(new java.awt.Color(255, 255, 255));
        LBMIN.setText("_");
        pm.add(LBMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -10, 20, 40));

        LBEXIT.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LBEXIT.setForeground(new java.awt.Color(255, 255, 255));
        LBEXIT.setText("X");
        pm.add(LBEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 20));

        getContentPane().add(pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 90));

        pm1.setBackground(new java.awt.Color(85, 85, 85));
        pm1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pm1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Notifikasi");
        pm1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 80, 30));

        getContentPane().add(pm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 650, 30));

        pm2.setBackground(new java.awt.Color(153, 153, 153));
        pm2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pm2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(listnamepm);

        pm2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 100));
        pm2.add(txtidppm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 130, -1));
        pm2.add(txtidpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 130, -1));
        pm2.add(txtidag, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 130, -1));
        pm2.add(txtsubpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 170, -1));
        pm2.add(txtjumlahpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 170, -1));
        pm2.add(txtnamappm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 170, -1));

        btdelpm.setText("DEL");
        pm2.add(btdelpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 60, 80));

        getContentPane().add(pm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 650, 100));

        pm3.setBackground(new java.awt.Color(85, 85, 85));
        pm3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pm3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DETAIL PRODUK MASUK");
        pm3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 230, 40));

        tbdetailpm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tbdetailpm);

        pm3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 310));

        btcetakpm.setText("Cetak");
        pm3.add(btcetakpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 10, 100, -1));

        getContentPane().add(pm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 350));

        setSize(new java.awt.Dimension(900, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bgmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgmenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bgmenuMouseClicked

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlogoutActionPerformed

    private void btkurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkurirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btkurirActionPerformed

    private void btpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpembelianActionPerformed

    private void btpengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpengirimanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpengirimanActionPerformed

    private void BtdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtdaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtdaftarActionPerformed

    private void btsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btsupplierActionPerformed

    private void btpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdminDPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdminDPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdminDPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdminDPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdminDPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btdaftar;
    private javax.swing.JLabel LBEXIT;
    private javax.swing.JLabel LBMIN;
    private javax.swing.JLabel bgmenu;
    private javax.swing.JButton btcetakpm;
    private javax.swing.JButton btdelpm;
    private javax.swing.JButton btkurir;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btpelanggan;
    private javax.swing.JButton btpembelian;
    private javax.swing.JButton btpengiriman;
    private javax.swing.JButton btsearchpm;
    private javax.swing.JButton btsupplier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listnamepm;
    private javax.swing.JPanel pm;
    private javax.swing.JPanel pm1;
    private javax.swing.JPanel pm2;
    private javax.swing.JPanel pm3;
    private javax.swing.JTable tbdetailpm;
    private javax.swing.JTextField txtidag;
    private javax.swing.JTextField txtidpm;
    private javax.swing.JTextField txtidppm;
    private javax.swing.JTextField txtjumlahpm;
    private javax.swing.JTextField txtnamappm;
    private javax.swing.JTextField txtsearchpm;
    private javax.swing.JTextField txtsubpm;
    // End of variables declaration//GEN-END:variables
}
