/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectakhir;

import base.Flogin;
import static com.mycompany.projectakhir.menuAdminHome.db;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import myConnection.DBO;
import myEntity.ProdukBaru;
import myEntity.Riwayat;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;

/**
 *
 * @author LENOVO
 */
public class menuGudang extends javax.swing.JFrame {

    DBO db = new DBO();
    Connection cnn = db.getConnection();
    Properties props = new Properties();

    /**
     * Creates new form Register
     */
    public menuGudang() {
        initComponents();
        table_updatep();
    }

    private void table_updatep() {
        int cc;

        try {
            PreparedStatement pst = cnn.prepareStatement("SELECT * FROM produk");
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData RSMD = rs.getMetaData();
            cc = RSMD.getColumnCount();
            DefaultTableModel model = (DefaultTableModel) tabelproduk.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int ii = 1; ii <= cc; ii++) {
                    v2.add(rs.getString("Id_Produk"));
                    v2.add(rs.getString("Id_Supplier"));
                    v2.add(rs.getString("Nama_Produk"));
                    v2.add(rs.getString("Stok"));
                    v2.add(rs.getString("harga_satuan"));
                }
                model.addRow(v2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(menuAdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            PreparedStatement pst = cnn.prepareStatement("SELECT * FROM detail_supply");
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData RSMD = rs.getMetaData();
            cc = RSMD.getColumnCount();
            DefaultTableModel model = (DefaultTableModel) tabelriwayat.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();

                for (int ii = 1; ii <= cc; ii++) {
                    v2.add(rs.getString("Id"));
                    v2.add(rs.getString("Id_Produk"));
                    v2.add(rs.getString("Id_Supplier"));
                    v2.add(rs.getString("Nama_Produk"));
                    v2.add(rs.getString("Stok"));
                    v2.add(rs.getString("Tanggal"));
                }
                model.addRow(v2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(menuAdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btlogout = new javax.swing.JButton();
        btpembelian = new javax.swing.JButton();
        btriwayatp = new javax.swing.JButton();
        bgmenu = new javax.swing.JLabel();
        produk = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        txtidproduk = new javax.swing.JTextField();
        txtidsupplier = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtnamaproduk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btkirim = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelproduk = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        btbersih = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        riwayat = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelriwayat = new javax.swing.JTable();
        btR = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 85, 85));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SPAREPART MOTOR");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GUDANG");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 30));

        btlogout.setBackground(new java.awt.Color(204, 204, 204));
        btlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btlogout.setText("LOG OUT");
        btlogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 90, 30));

        btpembelian.setBackground(new java.awt.Color(85, 85, 85));
        btpembelian.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btpembelian.setForeground(new java.awt.Color(255, 255, 255));
        btpembelian.setText("Data Produk");
        btpembelian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpembelianActionPerformed(evt);
            }
        });
        jPanel2.add(btpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, -1));

        btriwayatp.setBackground(new java.awt.Color(85, 85, 85));
        btriwayatp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btriwayatp.setForeground(new java.awt.Color(255, 255, 255));
        btriwayatp.setText("Riwayat Produk masuk");
        btriwayatp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btriwayatp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btriwayatpActionPerformed(evt);
            }
        });
        jPanel2.add(btriwayatp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 250, -1));

        bgmenu.setBackground(new java.awt.Color(0, 0, 0));
        bgmenu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        bgmenu.setForeground(new java.awt.Color(255, 255, 255));
        bgmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sparepart.jpg"))); // NOI18N
        bgmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgmenuMouseClicked(evt);
            }
        });
        jPanel2.add(bgmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 340, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 570));

        produk.setVisible(true);
        produk.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtidproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprodukActionPerformed(evt);
            }
        });
        jPanel1.add(txtidproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 270, -1));
        jPanel1.add(txtidsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 270, -1));

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 270, -1));
        jPanel1.add(txtnamaproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 270, -1));

        jLabel1.setText("Id Produk");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setText("Id Supplier");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel7.setText("Nama Produk");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel8.setText("Jumlah");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        btkirim.setText("Kirim");
        btkirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkirimActionPerformed(evt);
            }
        });
        jPanel1.add(btkirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 170, 40));

        tabelproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Produk", "Id Supplier", "Nama Produk", "Stok", "Harga Satuan"
            }
        ));
        jScrollPane2.setViewportView(tabelproduk);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 180));

        jLabel9.setText("Harga Satuan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 270, -1));

        btbersih.setText("Bersihkan");
        btbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbersihActionPerformed(evt);
            }
        });
        jPanel1.add(btbersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 170, 40));

        produk.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 540));

        jPanel3.setBackground(new java.awt.Color(85, 85, 85));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        produk.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, 40));

        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -40, 680, 720));

        riwayat.setVisible(true);
        riwayat.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(85, 85, 85));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelriwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Id Produk", "Id Supplier", "Nama Produk", "Stok", "Tanggal"
            }
        ));
        jScrollPane3.setViewportView(tabelriwayat);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 520));

        btR.setText("Refresh");
        btR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRActionPerformed(evt);
            }
        });
        jPanel4.add(btR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 80, -1));

        riwayat.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 640, 570));

        getContentPane().add(riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -40, 670, 620));

        setSize(new java.awt.Dimension(916, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bgmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgmenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bgmenuMouseClicked

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        Flogin fl = new Flogin();
        fl.setVisible(true);
        fl.setLocationRelativeTo(null);
        fl.setDefaultCloseOperation(Flogin.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_btlogoutActionPerformed

    private void btriwayatpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btriwayatpActionPerformed
        riwayat.setVisible(true);
        produk.setVisible(false);
    }//GEN-LAST:event_btriwayatpActionPerformed

    private void btpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpembelianActionPerformed

        // TODO add your handling code here:
        riwayat.setVisible(false);
        produk.setVisible(true);
    }//GEN-LAST:event_btpembelianActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void btkirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkirimActionPerformed

        String idproduk, idsupplier, namaproduk, stok, harga;

        idproduk = txtidproduk.getText();
        idsupplier = txtidsupplier.getText();
        namaproduk = txtnamaproduk.getText();
        stok = txtjumlah.getText();
        harga = txtharga.getText();

        ProdukBaru pb = new ProdukBaru();
        pb.setIdproduk(idproduk);
        pb.setIdsupplier(idsupplier);
        pb.setNamaproduk(namaproduk);
        pb.setStok(stok);
        pb.setHarga(harga);
        try (Producer<String, String> producer = new org.apache.kafka.clients.producer.KafkaProducer<>(props)) {
            producer.send(new ProducerRecord<>("dataproduk", "", pb.toString())
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal mengirim data: " + e.getMessage());
        }
        table_updatep();
        
        Riwayat ri = new Riwayat();
        ri.setIdproduk(idproduk);
        ri.setIdsupplier(idsupplier);
        ri.setNamaproduk(namaproduk);
        ri.setStok(stok);
        
        try (Producer<String, String> producer = new org.apache.kafka.clients.producer.KafkaProducer<>(props)) {
            producer.send(new ProducerRecord<>("detaillpm", "", ri.toString())
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal mengirim data: " + e.getMessage());
        }
        kosongkan();
    }//GEN-LAST:event_btkirimActionPerformed

    private void btbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbersihActionPerformed
        // TODO add your handling code here:
        kosongkan();

    }//GEN-LAST:event_btbersihActionPerformed

    private void txtidprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprodukActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        props.put("bootstrap.servers", "192.168.100.7:9092, 192.168.100.164:9093");
        props.put("linger.ms", 1);
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

    }//GEN-LAST:event_formWindowOpened

    private void btRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRActionPerformed
        // TODO add your handling code here:
        table_updatep();
    }//GEN-LAST:event_btRActionPerformed

    private void kosongkan() {
        txtharga.setText("");
        txtidsupplier.setText("");
        txtidproduk.setText("");
        txtjumlah.setText("");
        txtnamaproduk.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgmenu;
    private javax.swing.JButton btR;
    private javax.swing.JButton btbersih;
    private javax.swing.JButton btkirim;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btpembelian;
    private javax.swing.JButton btriwayatp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JInternalFrame produk;
    private javax.swing.JInternalFrame riwayat;
    private javax.swing.JTable tabelproduk;
    private javax.swing.JTable tabelriwayat;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidproduk;
    private javax.swing.JTextField txtidsupplier;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnamaproduk;
    // End of variables declaration//GEN-END:variables
}
