/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectakhir;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class menuCostumer extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public menuCostumer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtidproduk = new javax.swing.JTextField();
        txtidpelanggan = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btkirim = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelproduk = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtpengambilan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btlogout = new javax.swing.JButton();
        btpembelian = new javax.swing.JButton();
        btriwayatp = new javax.swing.JButton();
        bgmenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LBEXIT = new javax.swing.JLabel();
        LBMIN = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtidproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 270, -1));
        jPanel1.add(txtidpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 270, -1));

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 270, -1));
        jPanel1.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 270, -1));

        jLabel1.setText("Id Produk");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setText("Id Pelanggan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel7.setText("Tanggal Pembelian");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel8.setText("Jumlah Produk");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        btkirim.setText("Kirim");
        jPanel1.add(btkirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 170, 40));

        tabelproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(tabelproduk);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 180));

        jLabel9.setText("Harga");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel10.setText("Pengambilan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 270, -1));
        jPanel1.add(txtpengambilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 270, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 650, 540));

        jPanel2.setBackground(new java.awt.Color(85, 85, 85));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SPAREPART MOTOR");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COSTUMER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, 30));

        btlogout.setBackground(new java.awt.Color(204, 204, 204));
        btlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btlogout.setText("LOG OUT");
        btlogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btlogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 90, 30));

        btpembelian.setBackground(new java.awt.Color(85, 85, 85));
        btpembelian.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btpembelian.setForeground(new java.awt.Color(255, 255, 255));
        btpembelian.setText("Pembelian");
        btpembelian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpembelianActionPerformed(evt);
            }
        });
        jPanel2.add(btpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, -1));

        btriwayatp.setBackground(new java.awt.Color(85, 85, 85));
        btriwayatp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btriwayatp.setForeground(new java.awt.Color(255, 255, 255));
        btriwayatp.setText("Riwayat Pembelian");
        btriwayatp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btriwayatp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btriwayatpActionPerformed(evt);
            }
        });
        jPanel2.add(btriwayatp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 250, -1));

        bgmenu.setBackground(new java.awt.Color(0, 0, 0));
        bgmenu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        bgmenu.setForeground(new java.awt.Color(255, 255, 255));
        bgmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sparepart.jpg"))); // NOI18N
        bgmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgmenuMouseClicked(evt);
            }
        });
        jPanel2.add(bgmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 340, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 570));

        jPanel3.setBackground(new java.awt.Color(85, 85, 85));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBEXIT.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        LBEXIT.setForeground(new java.awt.Color(255, 255, 255));
        LBEXIT.setText("X");
        jPanel3.add(LBEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, 30));

        LBMIN.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LBMIN.setForeground(new java.awt.Color(255, 255, 255));
        LBMIN.setText("_");
        jPanel3.add(LBMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -30, 10, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 30));

        setSize(new java.awt.Dimension(900, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bgmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgmenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bgmenuMouseClicked

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btlogoutActionPerformed

    private void btriwayatpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btriwayatpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btriwayatpActionPerformed

    private void btpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpembelianActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCostumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBEXIT;
    private javax.swing.JLabel LBMIN;
    private javax.swing.JLabel bgmenu;
    private javax.swing.JButton btkirim;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btpembelian;
    private javax.swing.JButton btriwayatp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelproduk;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidpelanggan;
    private javax.swing.JTextField txtidproduk;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtpengambilan;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
